### ISSUE TITLE
NeoForge doesn't start with Vortex Launcher

### ISSUE THREAD

**Issue by vitalif** [Kron4ek/minecraft-vortex-launcher#93] opened 2024-11-30 13:30 UTC
Hi
When I try to run NeoForge 1.21.1 using Vortex Launcher, java just exits and doesn't print anything. Log is also not created
Could you try it yourself and fix it please? )
Or could you at least give me a hint where I need to look and I can try to fix it myself and submit a PR... :-)

**Comment by Kron4ek** [comment] 2024-12-01 11:03
Hi. Yes, i can confirm that there are issues with launching NeoForge and new Fabric versions, maybe i will fix this.

**Comment by Kron4ek** [comment] 2024-12-06 13:55
Fixed in the latest release, thanks for the report.

**Closed by Kron4ek** 2024-12-06 13:55 UTC

**Comment by vitalif** [comment] 2024-12-07 10:04
Cool, it works now! Thanks :)

**Comment by re3lex** [comment] 2025-04-13 07:18
Hey! updated launcher to 1.1.20 version, but still cannot start the game with neoforge v21.1.146 since launcher is just closing silently.

Any idea what's wrong?

**Comment by vitalif** [comment] 2025-04-13 07:24
Same for me, now it works with neoforge 1.20.3 but not 1.20.1 - it's the same bug, it adds some libraries twice, both into -p and -cp

If you're on windows then the workaround is to save the launch string to file, rename it to start.bat and replace javaw.exe with java.exe in it, then try to run it in cmd. You'll see the actual error

@Kron4ek we're kindly asking for a fix :)
